# Exported classes -------------------------------------------------------------

# NOTE: This create a 'classGeneratorFunction' (internal constructor), .BSseq()
.BSseq_mod <- setClass(
    "BSseq_mod",
    slots = representation(
        trans = "function",
        parameters = "list"),
    contains = "RangedSummarizedExperiment"
)

# Exported functions -----------------------------------------------------------

# BSseq class object for handling other modification calls generated by modkit
BSseq_mod <- function(M = NULL, U = NULL, Other_mod = NULL, Filtered = NULL,
                      coef = NULL, se.coef = NULL,
                      trans = NULL, parameters = NULL, pData = NULL, gr = NULL,
                      pos = NULL, chr = NULL, sampleNames = NULL,
                      rmZeroCov = FALSE) {

  # Argument checks ----------------------------------------------------------

  # Process assays.
  # NOTE: Nothing to do for 'coef', and 'se.coef'.
  if (is.null(M) || is.null(U) || is.null(Other_mod)) {
    stop("Need 'M', 'U' and 'Other_mod'.")
  }
  # Process 'trans' and 'parameters'.
  if (is.null(trans)) {
    trans <- function() NULL
    environment(trans) <- emptyenv()
  }
  if (is.null(parameters)) {
    parameters <- list()
  }
  # Process 'sampleNames' and 'pData'.
  if (is.null(sampleNames)) {
    if (is.null(pData)) {
      # BSseq object will have no colnames.
      pData <- make_zero_col_DFrame(ncol(M))
    } else {
      # BSseq object will have 'sampleNames' as colnames.
      pData <- DataFrame(row.names = sampleNames)
    }
  } else {
    if (is.null(pData)) {
      # BSseq object will have 'sampleNames' as colnames.
      pData <- DataFrame(row.names = sampleNames)
    } else {
      if (is.null(rownames(pData))) {
        rownames(pData) <- sampleNames
      } else {
        stopifnot(identical(rownames(pData), sampleNames))
      }
    }
  }
  # Process 'gr', 'pos', and 'chr'.
  if (is.null(gr)) {
    if (is.null(pos) || is.null(chr)) {
      stop("Need 'pos' and 'chr' if 'gr' not supplied.")
    }
    gr <- GRanges(seqnames = chr, ranges = IRanges(start = pos, width = 1L))
  }
  if (!is(gr, "GRanges")) {
    stop("'gr' needs to be a GRanges.")
  }
  # Process 'rmZeroCov'.
  stopifnot(isTRUEorFALSE(rmZeroCov))

  # Collapse duplicate loci --------------------------------------------------

  is_duplicated <- duplicated(gr)
  if (any(is_duplicated)) {
    warning("Detected duplicate loci. Collapsing counts in 'M', 'U', and 'Other_mod'",
            "at these positions.")
    if (!is.null(coef) || !is.null(se.coef)) {
      stop("Cannot collapse when 'coef' or 'se.coef' are non-NULL.")
    }
    loci <- gr[!is_duplicated]
    ol <- findOverlaps(gr, loci, type = "equal")
    M <- rowsum(x = M, group = subjectHits(ol), reorder = FALSE)
    rownames(M) <- NULL
    U <- rowsum(x = U, group = subjectHits(ol), reorder = FALSE)
    rownames(U) <- NULL
    Other_mod <- rowsum(x = Other_mod, group = subjectHits(ol), reorder = FALSE)
    rownames(Other_mod) <- NULL
    if (!is.null(Filtered)){
      Filtered <- rowsum(x = Filtered, group = subjectHits(ol), reorder = FALSE)
      rownames(Filtered) <- NULL}
  } else {
    loci <- gr
  }

  # Optionally, remove positions with zero coverage --------------------------

  if (rmZeroCov) {
    loci_with_zero_cov <- rowAlls((U + M + Other_mod), value = 0)
    if (any(loci_with_zero_cov)) {
      loci_with_nonzero_cov <- !loci_with_zero_cov
      gr <- gr[loci_with_nonzero_cov]
      M <- M[loci_with_nonzero_cov, , drop = FALSE]
      U <- U[loci_with_nonzero_cov, , drop = FALSE]
      coef <- coef[loci_with_nonzero_cov, , drop = FALSE]
      se.coef <- se.coef[loci_with_nonzero_cov, , drop = FALSE]
      Filtered <- Filtered[loci_with_nonzero_cov, , drop = FALSE]
      Other_mod <- Other_mod[loci_with_nonzero_cov, , drop = FALSE]
    }
  }

  # Construct BSseq object ---------------------------------------------------

  assays <- SimpleList(M = M, U = U, Filtered = Filtered, Other_mod = Other_mod,
                       coef = coef, se.coef = se.coef)
  assays <- assays[!S4Vectors:::sapply_isNULL(assays)]
  se <- SummarizedExperiment(
    assays = assays,
    rowRanges = loci,
    colData = pData)
  .BSseq_mod(se, trans = trans, parameters = parameters)
}

hasBeenSmoothed_mod <- function(BSseq_mod) {
    "coef" %in% assayNames(BSseq_mod)
}

getBSseq_mod <- function(BSseq_mod,
                     type = c("U", "M", "Other_mod", "Filtered", "gr", "coef",
                              "se.coef", "trans", "parameters"),
                     withDimnames = TRUE) {
    type <- match.arg(type)
    if (type %in% c("M", "U", "Other_mod")) {
        return(assay(BSseq_mod, type, withDimnames = withDimnames))
    }
    if (type %in% c("Filtered", "coef", "se.coef")) {
        if (type %in% assayNames(BSseq_mod)) {
            return(assay(BSseq_mod, type, withDimnames = withDimnames))
        } else {
            return(NULL)
        }
    }
    if (type == "trans") {
        return(BSseq_mod@trans)
    }
    if (type == "parameters") {
        return(BSseq_mod@parameters)
    }
    if (type == "gr") {
        return(BSseq_mod@rowRanges)
    }
}

strandCollapse_mod <- function(BSseq_mod, shift = TRUE, BPPARAM = bpparam(),
                           BACKEND = getAutoRealizationBackend(),
                           dir = tempfile("BSseq_mod"), replace = FALSE,
                           chunkdim = NULL, level = NULL,
                           type = c("double", "integer")) {

    # Argument checks ----------------------------------------------------------

    if (all(runValue(strand(BSseq_mod)) == "*")) {
        warning("All loci are unstranded, nothing to collapse.", call. = FALSE)
        return(BSseq_mod)
    }
    if (!(all(runValue(strand(BSseq_mod)) %in% c("+", "-")))) {
        stop("'BSseq' object has a mix of stranded and unstranded loci.")
    }
    # Register 'BACKEND' and return to current value on exit.
    # TODO: Is this strictly necessary?
    current_BACKEND <- getAutoRealizationBackend()
    on.exit(setAutoRealizationBackend(current_BACKEND), add = TRUE)
    setAutoRealizationBackend(BACKEND)
    # Check compatability of 'BPPARAM' with 'BACKEND'.
    if (!.areBackendsInMemory(BACKEND)) {
        if (!.isSingleMachineBackend(BPPARAM)) {
            stop("The parallelisation strategy must use a single machine ",
                 "when using an on-disk realization backend.\n",
                 "See help(\"read.bismark\") for details.",
                 call. = FALSE)
        }
    } else {
        if (!is.null(BACKEND)) {
            # NOTE: Currently do not support any in-memory realization
            #       backends. If the realization backend is NULL then an
            #       ordinary matrix is returned rather than a matrix-backed
            #       DelayedMatrix.
            stop("The '", BACKEND, "' realization backend is not supported.",
                 "\n  See help(\"read.bismark\") for details.",
                 call. = FALSE)
        }
    }
    # If using HDF5Array as BACKEND, check remaining options are sensible.
    if (identical(BACKEND, "HDF5Array")) {
        # NOTE: Most of this copied from
        #       HDF5Array::saveHDF5SummarizedExperiment().
        if (!isSingleString(dir)) {
            stop(wmsg("'dir' must be a single string specifying the path to ",
                      "the directory where to save the BSseq object (the ",
                      "directory will be created)."))
        }
        if (!isTRUEorFALSE(replace)) {
            stop("'replace' must be TRUE or FALSE")
        }
        if (!dir.exists(dir)) {
            HDF5Array::create_dir(dir)
        } else {
            HDF5Array::replace_dir(dir, replace)
        }
        h5_path <- file.path(dir, "assays.h5")
    } else if (identical(BACKEND, NULL)) {
        h5_path <- NULL
    }

    # Collapse loci ------------------------------------------------------------

    loci <- rowRanges(BSseq_mod)
    if (shift) {
        loci <- shift(loci, shift = as.integer(-1L * (strand(loci) == "-")))
    }
    collapsed_loci <- reduce(loci, min.gapwidth = 0L, ignore.strand = TRUE)

    # Collapse 'M', 'U' and ' Other_mod' matrices ------------------------------

    ol <- findOverlaps(loci, collapsed_loci, type = "equal")
    group <- subjectHits(ol)
    M <- .rowsum(
        x = assay(BSseq_mod, "M", withDimnames = FALSE),
        group = group,
        # NOTE: reorder = TRUE to ensure same row-order as collapsed_loci.
        reorder = TRUE,
        BPPARAM = BPPARAM,
        filepath = h5_path,
        name = "M",
        chunkdim = chunkdim,
        level = level,
        type = type)
    U <- .rowsum(
        x = assay(BSseq_mod, "U", withDimnames = FALSE),
        group = group,
        # NOTE: reorder = TRUE to ensure same row-order as collapsed_loci.
        reorder = TRUE,
        BPPARAM = BPPARAM,
        filepath = h5_path,
        name = "U",
        chunkdim = chunkdim,
        level = level,
        type = type)
    Other_mod <- .rowsum(
        x = assay(BSseq_mod, "Other_mod", withDimnames = FALSE),
        group = group,
        # NOTE: reorder = TRUE to ensure same row-order as collapsed_loci.
        reorder = TRUE,
        BPPARAM = BPPARAM,
        filepath = h5_path,
        name = "Other_mod",
        chunkdim = chunkdim,
        level = level,
        type = type)

    # Construct BSseq object, saving it if it is HDF5-backed -------------------

    se <- SummarizedExperiment(
        assays = SimpleList(M = unname(M), U = unname(U),
                            Other_mod = unname(Other_mod)),
        rowRanges = collapsed_loci,
        colData = colData(BSseq_mod))
    # TODO: Is there a way to use the internal constructor with `check = FALSE`?
    #       Assuming input was valid, the output is valid, too.
    # .BSseq(se, trans = function(x) NULL, parameters = list())
    bsseq_mod <- new2("BSseq_mod", se, check = FALSE)
    if (!is.null(BACKEND) && BACKEND == "HDF5Array") {
        # NOTE: Save BSseq object; mimicing
        #       HDF5Array::saveHDF5SummarizedExperiment().
        x <- bsseq_mod
        x@assays <- HDF5Array::shorten_assay2h5_links(x@assays)
        saveRDS(x, file = file.path(dir, "se.rds"))
    }
    bsseq_mod
}

# Exported methods -------------------------------------------------------------

setMethod("show", signature(object = "BSseq_mod"), function(object) {
    cat("An object of type 'Modified BSseq' with\n")
    cat(" ", nrow(object), "methylation loci\n")
    cat(" ", ncol(object), "samples\n")
    if (hasBeenSmoothed(object)) {
        cat("has been smoothed with\n")
        cat(" ", object@parameters$smoothText, "\n")
    } else {
        cat("has not been smoothed\n")
    }
    if (.isHDF5ArrayBacked(object)) {
        cat("Some assays are HDF5Array-backed\n")
    } else {
        cat("All assays are in-memory\n")
    }
})

setMethod("pData", "BSseq_mod", function(object) {
    object@colData
})

setReplaceMethod(
    "pData",
    signature = signature(object = "BSseq_mod", value = "data.frame"),
    function(object, value) {
        colData(object) <- as(value, "DataFrame")
        object
    }
)

setReplaceMethod(
    "pData",
    signature = signature(object = "BSseq_mod", value = "DataFrame"),
    function(object, value) {
        colData(object) <- value
        object
    }
)

setMethod("sampleNames", "BSseq_mod", function(object) colnames(object))

setReplaceMethod(
    "sampleNames",
    signature = signature(object = "BSseq_mod", value = "ANY"),
    function(object, value) {
        colnames(object) <- value
        object
    }
)

setMethod("updateObject", "BSseq_mod",
          function(object, ...) {
              # NOTE: identical() is too strong
              if (hasBeenSmoothed(object) &&
                  isTRUE(all.equal(getBSseq_mod(object, "trans"), .oldTrans))) {
                  object@trans <- plogis
              }
              if (is(object, "SummarizedExperiment")) {
                  # NOTE: Call method for SummarizedExperiment objects
                  object <- callNextMethod()
                  return(object)
              } else {
                  BSseq_mod(
                      gr = object@gr,
                      M = object@M,
                      U = object@U,
                      Other_mod = object@Other_mod,
                      coef = object@coef,
                      se.coef = object@se.coef,
                      trans = object@trans,
                      parameters = object@parameters,
                      pData = object@phenoData@data)
              }
          }
)

